# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47aa4e5a6f73ca2215b5144a3beb89b7673cb57a9c12d600243bafa904d6412deb061abf9cc0733d573a973b869086fe3d34592dea33df0279b93e8277a41b1f

test:
  secret_key_base: 6dfd724af51df743c4fd836d689fc2b814e96d7dbab45f703acb0f1baf08c120a19f449af547e6d164efa290071c5005daf906a209684a2470f67b446c3109b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
